### ISSUE TITLE
Is it possible to relelase current master?

### ISSUE THREAD

**Issue by MartinKocour** [junzis/pyopensky#3]
Hi guys, do you plan to release current master?

I am working on ATCO2 project and we are using pyopensky for retrieving callsigns. Currently I am using `OpenskyImpalaWrapper. rawquery()` Unfortunetly, this method is not released in current version 1.3.

**Comment by junzis** [comment]
Thanks for the suggestion @MartinKocour. Version 1.4 is with pip now. You can upgrade it:
```
pip install --upgrade pyopensky
```
