### ISSUE TITLE
Example with raw data returns "No record found"

### ISSUE THREAD

**Issue by MatthiasPoppe** [junzis/pyopensky#4]
Hello Junzi,
thanks for your excellent work regarding these useful libraries. When I tried your first example with the OpenskyImpalaWrapper retrieving raw messages, the following error occured:
* Server connection successful!
* Obtaining details of the query...
* OpenSky Impala: 0 of records found.
* No record found.
* Obtaining details of the query...
* OpenSky Impala: 0 of records found.
* No record found.

After changing to type=adsb, everything works fine. Any clue? Is this probably related to some maintenance/overhaul of the OpenSky Impala data base (Xavier O. pointed out to me that there may be some problems with Mode EHS data availbility). 
Regards,
Matthias

**Comment by ElSabio97** [comment]
I am having this very same issue with `test_ehs_helper.py`. I guess this is related to not having on the Impala tables before 2020.

**Comment by junzis** [comment]
Yes, I think there are some ongoing changes with OpenSky servers. Let's wait and see how it goes.
